/*
  Franchise / themed trivia banks — curated, high-confidence question sets for
  topic pages that target a specific franchise keyword (e.g. "harry potter
  trivia"). These are kept SEPARATE from the daily POOL on purpose: niche
  franchise questions should NOT leak into general Daily Trivia.

  Schema matches the rest of the app: the CORRECT answer is authored FIRST in
  `options`; option order is shuffled at runtime by shuffleQuiz().
*/

export const HARRY_POTTER = [
  { q: 'Which Hogwarts house is Harry Potter sorted into?', options: ['Gryffindor', 'Slytherin', 'Hufflepuff', 'Ravenclaw'], difficulty: 0 },
  { q: 'What is the name of Harry Potter\'s pet owl?', options: ['Hedwig', 'Errol', 'Pigwidgeon', 'Crookshanks'], difficulty: 0 },
  { q: 'Who wrote the Harry Potter book series?', options: ['J.K. Rowling', 'J.R.R. Tolkien', 'Suzanne Collins', 'Roald Dahl'], difficulty: 0 },
  { q: 'What position does Harry play on the Quidditch team?', options: ['Seeker', 'Keeper', 'Beater', 'Chaser'], difficulty: 1 },
  { q: 'What is the name of the dark wizard Harry must defeat?', options: ['Lord Voldemort', 'Gellert Grindelwald', 'Salazar Slytherin', 'Igor Karkaroff'], difficulty: 0 },
  { q: 'What spell is used to disarm an opponent?', options: ['Expelliarmus', 'Stupefy', 'Wingardium Leviosa', 'Lumos'], difficulty: 1 },
  { q: 'From which platform do students board the Hogwarts Express?', options: ['Platform Nine and Three-Quarters', 'Platform Nine', 'Platform Ten', 'Platform Seven and a Half'], difficulty: 0 },
  { q: 'Who is the headmaster of Hogwarts for most of the series?', options: ['Albus Dumbledore', 'Severus Snape', 'Minerva McGonagall', 'Cornelius Fudge'], difficulty: 0 },
  { q: 'What form does Harry\'s Patronus take?', options: ['A stag', 'A phoenix', 'An otter', 'A doe'], difficulty: 1 },
  { q: 'What is the name of Hagrid\'s three-headed dog?', options: ['Fluffy', 'Fang', 'Norbert', 'Buckbeak'], difficulty: 1 },
  { q: 'What is the incantation for the Killing Curse?', options: ['Avada Kedavra', 'Crucio', 'Sectumsempra', 'Imperio'], difficulty: 1 },
  { q: 'What is the name of the Weasley family home?', options: ['The Burrow', 'Grimmauld Place', 'The Shrieking Shack', 'Spinner\'s End'], difficulty: 1 },
  { q: 'Who is Harry\'s godfather?', options: ['Sirius Black', 'Remus Lupin', 'James Potter', 'Arthur Weasley'], difficulty: 1 },
  { q: 'What core is inside Harry\'s wand?', options: ['Phoenix feather', 'Dragon heartstring', 'Unicorn hair', 'Veela hair'], difficulty: 2 },
  { q: 'What does the spell "Lumos" do?', options: ['Lights the tip of the wand', 'Unlocks a door', 'Mends broken objects', 'Levitates an object'], difficulty: 0 },
  { q: 'What is the wizarding bank called?', options: ['Gringotts', 'Flourish and Blotts', 'Ollivanders', 'Borgin and Burkes'], difficulty: 1 },
  { q: 'What magical object does Hermione use to attend extra classes in Prisoner of Azkaban?', options: ['A Time-Turner', 'The Marauder\'s Map', 'A Pensieve', 'A Remembrall'], difficulty: 2 },
  { q: 'What is the name of the house-elf freed by Harry in the second book?', options: ['Dobby', 'Kreacher', 'Winky', 'Hokey'], difficulty: 1 },
  { q: 'Into how many pieces did Voldemort intend to split his soul?', options: ['Seven', 'Three', 'Five', 'Twelve'], difficulty: 2 },
  { q: 'What is the wizarding prison guarded by Dementors called?', options: ['Azkaban', 'Nurmengard', 'The Ministry', 'Knockturn Alley'], difficulty: 1 },
  { q: 'What does the Marauder\'s Map reveal?', options: ['Everyone\'s location inside Hogwarts', 'Hidden treasure', 'The future', 'Secret spells'], difficulty: 1 },
  { q: 'What is Draco Malfoy\'s Hogwarts house?', options: ['Slytherin', 'Gryffindor', 'Ravenclaw', 'Hufflepuff'], difficulty: 0 },
  { q: 'What hidden London street is the wizarding shopping district?', options: ['Diagon Alley', 'Knockturn Alley', 'Privet Drive', 'Godric\'s Hollow'], difficulty: 1 },
  { q: 'What are the gold coins of the wizarding currency called?', options: ['Galleons', 'Sickles', 'Knuts', 'Florins'], difficulty: 2 },
  { q: 'Which French school competes in the Triwizard Tournament?', options: ['Beauxbatons', 'Durmstrang', 'Ilvermorny', 'Mahoutokoro'], difficulty: 2 },
  { q: 'Who is the Potions master and head of Slytherin house?', options: ['Severus Snape', 'Horace Slughorn', 'Gilderoy Lockhart', 'Quirinus Quirrell'], difficulty: 1 },
  { q: 'What sport is played on broomsticks at Hogwarts?', options: ['Quidditch', 'Gobstones', 'Wizard\'s Chess', 'Quodpot'], difficulty: 0 },
  { q: 'What is the name of Ron Weasley\'s pet rat?', options: ['Scabbers', 'Hedwig', 'Trevor', 'Nagini'], difficulty: 1 },
  { q: 'Which Deathly Hallow makes the wearer invisible?', options: ['The Cloak of Invisibility', 'The Elder Wand', 'The Resurrection Stone', 'The Sorting Hat'], difficulty: 1 },
  { q: 'What creature is Buckbeak?', options: ['A Hippogriff', 'A Thestral', 'A Phoenix', 'A Basilisk'], difficulty: 1 },
  { q: 'What is the name of the giant snake in the Chamber of Secrets?', options: ['Basilisk', 'Nagini', 'Aragog', 'Norbert'], difficulty: 1 },
  { q: 'Who teaches Defence Against the Dark Arts in Prisoner of Azkaban?', options: ['Remus Lupin', 'Gilderoy Lockhart', 'Mad-Eye Moody', 'Dolores Umbridge'], difficulty: 2 },
];

export const DISNEY = [
  { q: 'In which film does a wooden puppet wish to become a real boy?', options: ['Pinocchio', 'Peter Pan', 'Dumbo', 'Bambi'], difficulty: 0 },
  { q: 'What is the name of the clownfish father searching for his son?', options: ['Marlin', 'Nemo', 'Dory', 'Gill'], difficulty: 1 },
  { q: 'Which Disney princess has a pet tiger named Rajah?', options: ['Jasmine', 'Ariel', 'Mulan', 'Belle'], difficulty: 1 },
  { q: 'In The Lion King, what is the name of Simba’s villainous uncle?', options: ['Scar', 'Mufasa', 'Zazu', 'Rafiki'], difficulty: 0 },
  { q: 'What is the name of the cowboy doll in Toy Story?', options: ['Woody', 'Buzz', 'Rex', 'Hamm'], difficulty: 0 },
  { q: 'Which Disney villain wants to make a coat from dalmatian puppies?', options: ['Cruella de Vil', 'Maleficent', 'Ursula', 'The Evil Queen'], difficulty: 1 },
  { q: 'In Beauty and the Beast, what object is the character Lumiere?', options: ['A candelabra', 'A clock', 'A teapot', 'A wardrobe'], difficulty: 1 },
  { q: 'What is the name of the demigod in Moana?', options: ['Maui', 'Tamatoa', 'Chief Tui', 'Heihei'], difficulty: 1 },
  { q: 'Which film features the song “Let It Go”?', options: ['Frozen', 'Tangled', 'Encanto', 'Moana'], difficulty: 0 },
  { q: 'What is the name of the little mermaid?', options: ['Ariel', 'Aurora', 'Jasmine', 'Belle'], difficulty: 0 },
  { q: 'What is the name of the rat who dreams of being a chef in a Pixar film?', options: ['Remy', 'Emile', 'Linguini', 'Django'], difficulty: 1 },
  { q: 'In Cinderella, what is turned into a coach by the Fairy Godmother?', options: ['A pumpkin', 'A mouse', 'A melon', 'A carriage horse'], difficulty: 0 },
  { q: 'What is the name of Mickey Mouse’s pet dog?', options: ['Pluto', 'Goofy', 'Max', 'Toby'], difficulty: 0 },
  { q: 'What is the name of the toy space ranger in Toy Story?', options: ['Buzz Lightyear', 'Woody', 'Zurg', 'Rex'], difficulty: 0 },
  { q: 'In Aladdin, what is the name of the monkey?', options: ['Abu', 'Iago', 'Rajah', 'Jafar'], difficulty: 1 },
  { q: 'What is the name of the snowman in Frozen?', options: ['Olaf', 'Sven', 'Kristoff', 'Marshmallow'], difficulty: 0 },
  { q: 'In Sleeping Beauty, what is the princess’s name?', options: ['Aurora', 'Snow White', 'Cinderella', 'Tiana'], difficulty: 1 },
  { q: 'Which classic Disney film features seven dwarfs?', options: ['Snow White and the Seven Dwarfs', 'Cinderella', 'Pinocchio', 'Bambi'], difficulty: 0 },
  { q: 'In The Jungle Book, what kind of animal is Baloo?', options: ['A bear', 'A panther', 'A tiger', 'A wolf'], difficulty: 1 },
  { q: 'Who provided the voice of the Genie in the 1992 film Aladdin?', options: ['Robin Williams', 'Eddie Murphy', 'Jim Carrey', 'Billy Crystal'], difficulty: 2 },
  { q: 'What is the name of Woody’s owner in Toy Story?', options: ['Andy', 'Sid', 'Bonnie', 'Al'], difficulty: 1 },
  { q: 'Which Disney film is set in the kingdom of Arendelle?', options: ['Frozen', 'Brave', 'Tangled', 'Cinderella'], difficulty: 1 },
  { q: 'What kind of animal is Dumbo?', options: ['An elephant', 'A mouse', 'A donkey', 'A bear'], difficulty: 0 },
  { q: 'In Tangled, what is magical about Rapunzel’s long hair?', options: ['It has healing powers', 'It can fly', 'It turns invisible', 'It never tangles'], difficulty: 1 },
  { q: 'What sea witch does Ariel make a deal with in The Little Mermaid?', options: ['Ursula', 'Maleficent', 'Cruella', 'Yzma'], difficulty: 1 },
  { q: 'Which film features a young lion named Simba?', options: ['The Lion King', 'Tarzan', 'The Jungle Book', 'Bambi'], difficulty: 0 },
  { q: 'In Finding Nemo, what type of fish is the forgetful Dory?', options: ['A blue tang', 'A clownfish', 'A pufferfish', 'A goldfish'], difficulty: 2 },
  { q: 'What is the name of the cricket who acts as Pinocchio’s conscience?', options: ['Jiminy Cricket', 'Timothy', 'Figaro', 'Cleo'], difficulty: 1 },
  { q: 'Which Disneyland park opened first, in 1955?', options: ['Disneyland in California', 'Walt Disney World in Florida', 'Disneyland Paris', 'Tokyo Disneyland'], difficulty: 2 },
  { q: 'What are the names of the two royal sisters in Frozen?', options: ['Elsa and Anna', 'Aurora and Merida', 'Rapunzel and Belle', 'Moana and Tiana'], difficulty: 0 },
];

export const MARVEL = [
  { q: 'What is the real name of Iron Man?', options: ['Tony Stark', 'Steve Rogers', 'Bruce Banner', 'Peter Parker'], difficulty: 0 },
  { q: 'What is Spider-Man’s alter ego?', options: ['Peter Parker', 'Tony Stark', 'Clark Kent', 'Bruce Wayne'], difficulty: 0 },
  { q: 'What metal coats Wolverine’s skeleton and claws?', options: ['Adamantium', 'Vibranium', 'Titanium', 'Uru'], difficulty: 2 },
  { q: 'What is the name of Thor’s hammer?', options: ['Mjolnir', 'Stormbreaker', 'Gungnir', 'Hofund'], difficulty: 1 },
  { q: 'Which fictional African nation is the home of Black Panther?', options: ['Wakanda', 'Sokovia', 'Genosha', 'Latveria'], difficulty: 1 },
  { q: 'Who is the villain seeking all the Infinity Stones in Avengers: Infinity War?', options: ['Thanos', 'Loki', 'Ultron', 'Red Skull'], difficulty: 0 },
  { q: 'How many Infinity Stones are there?', options: ['Six', 'Four', 'Five', 'Seven'], difficulty: 1 },
  { q: 'What is Captain America’s real name?', options: ['Steve Rogers', 'Bucky Barnes', 'Sam Wilson', 'Tony Stark'], difficulty: 1 },
  { q: 'What is the name of the talking raccoon in Guardians of the Galaxy?', options: ['Rocket', 'Groot', 'Drax', 'Star-Lord'], difficulty: 1 },
  { q: 'What is the only line the tree-like creature Groot usually says?', options: ['“I am Groot”', '“We are Groot”', '“I am Baby Groot”', '“Groot smash”'], difficulty: 0 },
  { q: 'What is the real name of the Hulk?', options: ['Bruce Banner', 'Tony Stark', 'Hank Pym', 'Reed Richards'], difficulty: 1 },
  { q: 'Spider-Man was bitten by what kind of spider?', options: ['A radioactive spider', 'A genetically modified spider', 'A venomous spider', 'An alien spider'], difficulty: 0 },
  { q: 'What is the name of Tony Stark’s AI assistant in the early Iron Man films?', options: ['JARVIS', 'FRIDAY', 'KAREN', 'EDITH'], difficulty: 2 },
  { q: 'What is the real name of Black Widow?', options: ['Natasha Romanoff', 'Wanda Maximoff', 'Carol Danvers', 'Pepper Potts'], difficulty: 1 },
  { q: 'Which superhero becomes a master of the mystic arts?', options: ['Doctor Strange', 'Iron Man', 'Hawkeye', 'Ant-Man'], difficulty: 1 },
  { q: 'What is the name of Thor’s adopted brother, the god of mischief?', options: ['Loki', 'Heimdall', 'Balder', 'Odin'], difficulty: 0 },
  { q: 'What metal is Captain America’s shield made from?', options: ['Vibranium', 'Adamantium', 'Steel', 'Uru'], difficulty: 1 },
  { q: 'Which superhero can shrink to the size of an insect?', options: ['Ant-Man', 'The Wasp', 'Spider-Man', 'Hawkeye'], difficulty: 1 },
  { q: 'What is the name of Tony Stark’s company?', options: ['Stark Industries', 'Oscorp', 'Pym Technologies', 'Roxxon'], difficulty: 1 },
  { q: 'Which agency does Nick Fury lead?', options: ['S.H.I.E.L.D.', 'A.I.M.', 'HYDRA', 'S.W.O.R.D.'], difficulty: 1 },
  { q: 'What is the name of the team that Iron Man and Captain America belong to?', options: ['The Avengers', 'The X-Men', 'The Justice League', 'The Defenders'], difficulty: 0 },
  { q: 'Which Avenger is an expert archer known for his bow and arrows?', options: ['Hawkeye', 'Black Widow', 'Falcon', 'Winter Soldier'], difficulty: 1 },
  { q: 'What is Black Panther’s name as king of Wakanda?', options: ['T’Challa', 'M’Baku', 'Killmonger', 'Shuri'], difficulty: 2 },
  { q: 'Which glove does Thanos use to hold the Infinity Stones?', options: ['The Infinity Gauntlet', 'The Power Glove', 'The Nano Gauntlet', 'The Iron Gauntlet'], difficulty: 1 },
  { q: 'What is the name of the school for mutants in the X-Men comics?', options: ['Xavier’s School for Gifted Youngsters', 'Hogwarts', 'The Avengers Academy', 'Midtown High'], difficulty: 2 },
  { q: 'Which Norse god of thunder is a founding Avenger?', options: ['Thor', 'Loki', 'Odin', 'Hela'], difficulty: 0 },
  { q: 'What color does Bruce Banner turn when he becomes the Hulk?', options: ['Green', 'Red', 'Blue', 'Grey'], difficulty: 0 },
  { q: 'Which villain with mechanical arms is a classic Spider-Man enemy?', options: ['Doctor Octopus', 'Green Goblin', 'Venom', 'The Vulture'], difficulty: 2 },
  { q: 'Which city does Spider-Man primarily protect?', options: ['New York City', 'Gotham City', 'Metropolis', 'Chicago'], difficulty: 0 },
  { q: 'Who created many Marvel characters and cameoed in nearly every MCU film?', options: ['Stan Lee', 'Jack Kirby', 'Steve Ditko', 'Walt Disney'], difficulty: 1 },
];

export const FRIENDS = [
  { q: 'What is the name of the coffee house where the friends hang out?', options: ['Central Perk', 'Café Nervosa', 'The Grind', 'Java Joe’s'], difficulty: 0 },
  { q: 'What is Ross Geller’s profession?', options: ['Palaeontologist', 'Chef', 'Actor', 'Lawyer'], difficulty: 1 },
  { q: 'What is Joey’s famous catchphrase greeting?', options: ['“How you doin’?”', '“Could I BE any more...?”', '“We were on a break!”', '“Oh. My. God.”'], difficulty: 0 },
  { q: 'What instrument does Phoebe play, badly, at Central Perk?', options: ['Guitar', 'Piano', 'Ukulele', 'Banjo'], difficulty: 1 },
  { q: 'What is the name of Phoebe’s famous song about a cat?', options: ['Smelly Cat', 'Sticky Shoe', 'Two of Them', 'Crazy Underwear'], difficulty: 0 },
  { q: 'Which character is famously obsessed with cleanliness and organisation?', options: ['Monica', 'Rachel', 'Phoebe', 'Janice'], difficulty: 0 },
  { q: 'Which two of the friends are siblings?', options: ['Ross and Monica', 'Joey and Chandler', 'Rachel and Phoebe', 'Ross and Chandler'], difficulty: 0 },
  { q: 'What is the name of Ross’s pet monkey?', options: ['Marcel', 'Mr. Heckles', 'Pat', 'Clunkers'], difficulty: 2 },
  { q: 'During his wedding to Emily, whose name does Ross say at the altar?', options: ['Rachel', 'Monica', 'Phoebe', 'Carol'], difficulty: 1 },
  { q: 'What is the name of Ross and Rachel’s daughter?', options: ['Emma', 'Ben', 'Erica', 'Leslie'], difficulty: 1 },
  { q: 'What does Rachel famously guess Chandler’s job is during a bet?', options: ['A “transponster”', 'A transponder', 'A data analyst', 'A statistician'], difficulty: 2 },
  { q: 'On which soap opera does Joey land a recurring acting role?', options: ['Days of Our Lives', 'General Hospital', 'The Bold and the Beautiful', 'All My Children'], difficulty: 1 },
  { q: 'Who did Rachel run away from at the altar in the very first episode?', options: ['Barry', 'Joshua', 'Tag', 'Paolo'], difficulty: 1 },
  { q: 'What is the one food Joey refuses to share?', options: ['All of it — Joey doesn’t share food', 'Pizza', 'Sandwiches', 'Meatball subs'], difficulty: 0 },
  { q: 'Which Central Perk barista is secretly in love with Rachel?', options: ['Gunther', 'Tag', 'Joshua', 'Mr. Heckles'], difficulty: 1 },
  { q: 'What is the name of Phoebe’s identical twin sister?', options: ['Ursula', 'Estelle', 'Bonnie', 'Amanda'], difficulty: 2 },
  { q: 'Who does Phoebe eventually marry?', options: ['Mike', 'David', 'Gary', 'Roger'], difficulty: 2 },
  { q: 'What pets do Joey and Chandler keep in their apartment?', options: ['A duck and a chick', 'A cat and a dog', 'A goldfish', 'A parrot'], difficulty: 1 },
  { q: 'In which city is Friends set?', options: ['New York City', 'Los Angeles', 'Chicago', 'Boston'], difficulty: 0 },
  { q: 'What is Chandler Bing’s unusual middle name?', options: ['Muriel', 'Maurice', 'Martin', 'Morris'], difficulty: 2 },
  { q: 'Ross and Rachel were famously “on a ___”.', options: ['Break', 'Date', 'Trip', 'Pause'], difficulty: 0 },
  { q: 'What is the name of Ross’s first wife, who leaves him for a woman?', options: ['Carol', 'Emily', 'Mona', 'Julie'], difficulty: 1 },
  { q: 'Where does Rachel get her big break in the fashion industry?', options: ['Ralph Lauren', 'Bloomingdale’s', 'Gucci', 'Louis Vuitton'], difficulty: 1 },
  { q: 'What is Monica’s profession?', options: ['Chef', 'Nurse', 'Teacher', 'Buyer'], difficulty: 1 },
  { q: 'By the end of the series, how many times has Ross been divorced?', options: ['Three', 'Two', 'Once', 'Four'], difficulty: 1 },
  { q: 'Which actress plays Rachel Green?', options: ['Jennifer Aniston', 'Courteney Cox', 'Lisa Kudrow', 'Reese Witherspoon'], difficulty: 1 },
  { q: 'Who lives across the hall from Monica and Rachel?', options: ['Joey and Chandler', 'Ross and Phoebe', 'Gunther', 'Mr. Heckles'], difficulty: 0 },
  { q: 'What item of clothing does Joey wear all at once to spite Chandler?', options: ['All of Chandler’s clothes', 'A wedding dress', 'A Santa suit', 'Rachel’s dress'], difficulty: 1 },
  { q: 'How many seasons of Friends were made?', options: ['Ten', 'Eight', 'Nine', 'Twelve'], difficulty: 1 },
  { q: 'What colour is the famous couch at Central Perk?', options: ['Orange', 'Red', 'Brown', 'Green'], difficulty: 1 },
];

